[jtbcnews_factcheck]
title = "JTBC 뉴스 ─ 팩트체크"
url = "https://news.jtbc.joins.com/factcheck/"
entrySelector = "div.bd.news_area ul li"
titleSelector = "div.news dl dt"
linkSelector = "div.news dl dt a"
contentSelector = "dl dd.desc a"
imageSelector = "div.news dl dd a img"